### PR TITLE
fix 2fa constant prompt

### LINKED ISSUE #162: 2FA Prompting continually
**Description**

I am continually being prompted for 2FA when running the command `hub-tool account info`. I'm sure there are other commands, but this doesn't seem to be a token TTL, but I can even re-use my OTP it happens so frequently 😄 

**Steps to reproduce the issue:**
1. login to Docker Desktop with Username + Password + 2FA
2. run `hub-tool account info` twice
3.

**Describe the results you received:**
```
❯ hub-tool account info
2FA required, please provide the 6 digit code: 123456
Username:       ahokanson
...

⛵  docker-desktop in ~ took 5s
❯ hub-tool account info
2FA required, please provide the 6 digit code: 123456
Username:       ahokanson
...
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `hub-tool --version`:**

```
❯ hub-tool version
Version:    v0.2.0
Git commit: 0edf43ac9091e7cac892cbc4cbc6efbafb665aa4
```

**Output of `docker version`:**

```
❯ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


```

**Output of `docker info`:**

```
❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: FUY4:P6OT:K6H7:FRWK:IOFJ:RR63:PVNI:RAY2:TESD:LQQS:DNEL:6SS4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker Desktop for Mac 
CleanShot 2021-01-28 at 11 11 36@2x

### PR DESCRIPTION
**Pull request by ingshtrom**
**- What I did**
- added some documentation for newer contributors and additional logging
- remove forced reprompt of OTP, so that we only re-prompt when the token is expired.

Fixes #162, or at least makes it less painful.

A little bit of background... 

Upon first login using the `2fa-login` endpoint, a token is returned which gives the user full access to all Hub APIs. When refreshing the token, the resulting token has _reduced_ permissions, and so some APIs that initially worked with the first token will now fail. Until the Hub API is modified to allow refreshed tokens to have the same access as the first token, we need to do another prompt of the user's OTP to get another token which gives the tool full access to the Hub APIs.

**- How I did it**
- removed the code that logs in for every "sudo" command. 

**- How to verify it**

Below is output from some commands I ran and the date when they were run to show it working. 

Here is the first run with a token that is expired.
```
❯ date -u && go run main.go account info
Mon Feb  1 15:12:18 UTC 2021
2FA required, please provide the 6 digit code: XXXXXX
Name:           ahokanson
Full name:      Alex Hokanson
Company:        Docker, Inc
Location:
Joined:         17 months ago
Plan:           free
Limits:
  Seats:                1/1
  Private repositories: 1/1
  Teams:                unlimited
  Collaborators:        unlimited
  Parallel builds:      1
```

Then we run it again within the TTL of the token (30 minutes) and no reprompting of the OTP is required.
```
❯ date -u && go run main.go account info
Mon Feb  1 15:12:39 UTC 2021
Name:           ahokanson
Full name:      Alex Hokanson
Company:        Docker, Inc
Location:
Joined:         17 months ago
Plan:           free
Limits:
  Seats:                1/1
  Private repositories: 1/1
  Teams:                unlimited
  Collaborators:        unlimited
  Parallel builds:      1
```

One last run shows that the token has expired, again, and we are correctly prompted to provide the OTP for 2FA authentication
```
❯ date -u && go run main.go account info
Mon Feb  1 15:56:01 UTC 2021
2FA required, please provide the 6 digit code: XXXXXX
Name:           ahokanson
Full name:      Alex Hokanson
Company:        Docker, Inc
Location:
Joined:         17 months ago
Plan:           free
Limits:
  Seats:                1/1
  Private repositories: 1/1
  Teams:                unlimited
  Collaborators:        unlimited
  Parallel builds:      1
```

**- Description for the changelog**
- added some documentation for newer contributors and additional logging
- remove forced reprompt of OTP. 

**- A picture of a cute animal (not mandatory)**
CleanShot 2021-02-01 at 11 13 23@2x

### CODE REVIEW

**Comment by ingshtrom** [comment]
PTAL @silvin-lubecki @rumpl

**Comment by silvin-lubecki** [comment]
@ingshtrom correct me if I'm wrong, but I think that this way all hub-tool commands will prompt for a 6-digit code if 2FA is enabled, right? It means the `sudo` annotations aren't used anymore? 🤔

**Comment by ingshtrom** [comment]
Good call. That isn't what we want. Although, that is likely what is already happening since https://github.com/docker/hub-tool/pull/167/files#diff-6830a710a038a65c376a407bfafe6dbcba1561c4994fcfb20aff88375403ac37R86 hasn't changed. I'll take a look at that and post a test here once I check it out. Thanks!

**Comment by silvin-lubecki** [comment]
I wonder if we can tell if the stored token is a refreshed token (with less rights) or a new token, with full rights. Maybe we should store refresh tokens and new tokens separately, and depending if the command is a `sudo` one or not, we take one token or the other 🤔 
It adds a lot of complexity, but I don't see any other option 😞

**Comment by ingshtrom** [comment]
stale, and I do not have any intention of working further on this

**Pull request closed without merging**
